### Criar um novo pedido (Testando o canalPedido)
POST http://localhost:8080/pedidos
Content-Type: application/json

{
  "clienteId": 1,
  "unidadeId": 1,
  "canalPedido": "TOTEM",
  "status": "AGUARDANDO_PAGAMENTO",
  "valorTotal": 89.90
}

### Listar todos os pedidos cadastrados
GET http://localhost:8080/pedidos


### Cadastrar um novo produto regional
POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nome": "Carne de Sol com Mandioca",
  "descricao": "Prato típico nordestino acompanhado de mandioca manteiga",
  "preco": 45.00
}

### Listar todos os produtos
GET http://localhost:8080/produtos


### Adicionar item ao pedido (Ex: Pedido ID 2, Produto ID 1)
POST http://localhost:8080/itens-pedido
Content-Type: application/json

{
  "pedidoId": 2,
  "produtoId": 1,
  "quantidade": 2,
  "precoUnitario": 45.00
}

### Listar itens de um pedido específico
GET http://localhost:8080/itens-pedido/pedido/2